// 90-candy seed list (provided by user, preserved order).
// - `query`     → OFF text search (CGI endpoint, ranked by text relevance)
// - `brand`     → required brand match for OFF
// - `nameMust`  → tokens that MUST appear in OFF product_name (avoids the
//                 wrong-product trap when a brand has many variants)
// - `imageOverride` → hand-curated Wikimedia Commons URL (highest priority)
// - `wikiTitle` → Wikipedia article (used by seed:wiki as fallback)

export type SeedCandy = {
  name: string;
  brand: string;
  query: string;
  barcode?: string;
  wikiTitle?: string;
  nameMust: string[];
  imageOverride?: string;
};

export const CANDY_LIST: SeedCandy[] = [
  { name: "Haribo Quaxi", brand: "Haribo", query: "Haribo Quaxi", nameMust: ["quaxi"], wikiTitle: "Haribo" },
  { name: "Chio Tortilla Chips Hot Chili", brand: "Chio", query: "Chio Tortilla Hot Chili", nameMust: ["tortilla", "chili"], wikiTitle: "Chio_Chips" },
  { name: "Center Shock Mystery", brand: "Storck", query: "Center Shock Mystery", nameMust: ["center", "shock"], wikiTitle: "Center_Shock" },
  { name: "Haribo Maoam Stripes", brand: "Haribo", query: "Maoam Stripes", nameMust: ["maoam", "stripes"], wikiTitle: "Maoam" },
  { name: "Kinder Country", brand: "Ferrero", query: "Kinder Country", nameMust: ["country"], wikiTitle: "Kinder_Country" },
  { name: "Duplo", brand: "Ferrero", query: "Duplo Ferrero", nameMust: ["duplo"], wikiTitle: "Duplo_(Süßware)" },
  { name: "Kinder Überraschungsei", brand: "Ferrero", query: "Kinder Überraschung", nameMust: ["überraschung", "ueberraschung", "surprise"], wikiTitle: "Überraschungsei" },
  { name: "Kinder Riegel", brand: "Ferrero", query: "Kinder Riegel", nameMust: ["kinder", "riegel"], wikiTitle: "Kinder_(Marke)" },
  { name: "Kinder Joy", brand: "Ferrero", query: "Kinder Joy", nameMust: ["joy"], wikiTitle: "Kinder_Joy", imageOverride: "https://commons.wikimedia.org/wiki/Special:FilePath/Kinder_Joy.png?width=600" },
  { name: "Mars Minis", brand: "Mars", query: "Mars Minis", nameMust: ["mars", "mini"], wikiTitle: "Mars_(Schokoriegel)" },
  { name: "Milky Way Minis", brand: "Mars", query: "Milky Way Minis", nameMust: ["milky", "way", "mini"], wikiTitle: "Milky_Way_(Schokoriegel)" },
  { name: "Skittles Fruits", brand: "Skittles", query: "Skittles Fruits", nameMust: ["skittles"], wikiTitle: "Skittles" },
  { name: "Nestlé Lion Riegel", brand: "Nestlé", query: "Lion Riegel", nameMust: ["lion"], wikiTitle: "Lion_(Schokoriegel)" },
  { name: "Bahlsen Leibniz Pick Up! Choco", brand: "Bahlsen", query: "Leibniz Pick Up Choco", nameMust: ["pick", "up"], wikiTitle: "Pick_Up!" },
  { name: "Kinder Bueno", brand: "Ferrero", query: "Kinder Bueno", nameMust: ["bueno"], wikiTitle: "Kinder_Bueno" },
  { name: "Oreo", brand: "Mondelez", query: "Oreo Doppelkeks", nameMust: ["oreo"], wikiTitle: "Oreo" },
  { name: "Haribo Lakritz Schnecken", brand: "Haribo", query: "Haribo Lakritzschnecken", nameMust: ["lakritz", "schnecke"], wikiTitle: "Haribo" },
  { name: "Niederegger Marzipan", brand: "Niederegger", query: "Niederegger Marzipan", nameMust: ["niederegger"], wikiTitle: "Niederegger_(Unternehmen)" },
  { name: "Trolli Saure Glühwürmchen", brand: "Trolli", query: "Trolli Glühwürmchen Saure", nameMust: ["glühwürm", "gluehwuerm", "glow"], wikiTitle: "Trolli" },
  { name: "Chio Chips Red Paprika", brand: "Chio", query: "Chio Chips Red Paprika", nameMust: ["chio", "paprika"], wikiTitle: "Chio_Chips" },
  { name: "DeBeukelaer Tourinos", brand: "DeBeukelaer", query: "DeBeukelaer Tourinos", nameMust: ["tourino"], wikiTitle: "DeBeukelaer" },
  { name: "Haribo Mega-Roulette", brand: "Haribo", query: "Haribo Mega Roulette", nameMust: ["roulette"], wikiTitle: "Haribo" },
  { name: "funny-frisch Chipsfrisch Ungarisch", brand: "funny-frisch", query: "funny frisch Chipsfrisch Ungarisch", nameMust: ["ungarisch"], wikiTitle: "Funny-frisch" },
  { name: "funny-frisch Kessel Chips", brand: "funny-frisch", query: "funny frisch Kessel Chips", nameMust: ["kessel"], wikiTitle: "Funny-frisch" },
  { name: "Original Sahne Muh-Muhs", brand: "Storck", query: "Sahne Muh-Muhs Storck", nameMust: ["muh"], wikiTitle: "August_Storck" },
  { name: "Funny Crazy Spray", brand: "Funny Candy", query: "Crazy Spray candy", nameMust: ["crazy", "spray"] },
  { name: "Ültje Erdnüsse gesalzen", brand: "Ültje", query: "Ültje Erdnüsse", nameMust: ["ültje", "ueltje"], wikiTitle: "Ültje" },
  { name: "Ferrero Giotto", brand: "Ferrero", query: "Ferrero Giotto", nameMust: ["giotto"], wikiTitle: "Giotto_(Süßware)" },
  { name: "Ferrero Rocher", brand: "Ferrero", query: "Ferrero Rocher", nameMust: ["rocher"], wikiTitle: "Ferrero_Rocher" },
  { name: "Wrigley's Spearmint", brand: "Wrigley's", query: "Wrigleys Spearmint", nameMust: ["spearmint"], wikiTitle: "Wrigley's_Spearmint" },
  { name: "Wrigley's Extra Professional Mints", brand: "Wrigley's", query: "Wrigleys Extra Professional Mints", nameMust: ["extra", "mint"], wikiTitle: "Extra_(Kaugummi)" },
  { name: "Storck Ice Fresh", brand: "Storck", query: "Storck Ice Fresh Bonbon", nameMust: ["ice", "fresh"] },
  { name: "Lay's Chips Paprika", brand: "Lay's", query: "Lays Paprika Chips", nameMust: ["lay"], wikiTitle: "Lay's" },
  { name: "M&M's Peanut", brand: "Mars", query: "M&M Peanut Erdnuss", nameMust: ["m&m", "peanut", "erdnuss"], wikiTitle: "M&M's" },
  { name: "M&M's Choco", brand: "Mars", query: "M&M Choco", nameMust: ["m&m"], wikiTitle: "M&M's" },
  { name: "TUC Cracker Original", brand: "TUC", query: "TUC Cracker Original", nameMust: ["tuc"], wikiTitle: "TUC_(Cracker)" },
  { name: "Nestlé Smarties", brand: "Nestlé", query: "Smarties Nestle", nameMust: ["smarties"], wikiTitle: "Smarties" },
  { name: "Chupa Chups Crazy Dips", brand: "Chupa Chups", query: "Chupa Chups Crazy Dips", nameMust: ["crazy", "dips", "chupa"], wikiTitle: "Chupa_Chups" },
  { name: "Bounty Riegel", brand: "Mars", query: "Bounty Riegel", nameMust: ["bounty"], wikiTitle: "Bounty_(Schokoriegel)" },
  { name: "Chupa Chups Frucht", brand: "Chupa Chups", query: "Chupa Chups Frucht", nameMust: ["chupa"], wikiTitle: "Chupa_Chups" },
  { name: "Daim XL", brand: "Mondelez", query: "Daim XL chocolate", nameMust: ["daim"], wikiTitle: "Daim", imageOverride: "https://commons.wikimedia.org/wiki/Special:FilePath/Daim-Bar-Split.jpg?width=600" },
  { name: "Hanuta", brand: "Ferrero", query: "Hanuta", nameMust: ["hanuta"], wikiTitle: "Hanuta" },
  { name: "Kinder Schoko-Bons", brand: "Ferrero", query: "Kinder Schoko-Bons", nameMust: ["schoko-bons", "schoko bons", "schokobon"], wikiTitle: "Kinder_Schoko-Bons" },
  { name: "Kinder Happy Hippo Cacao", brand: "Ferrero", query: "Kinder Happy Hippo Cacao", nameMust: ["hippo"], wikiTitle: "Kinder_(Marke)" },
  { name: "Kit Kat", brand: "Nestlé", query: "KitKat", nameMust: ["kit kat", "kitkat"], wikiTitle: "KitKat" },
  { name: "Leibniz Butterkeks", brand: "Bahlsen", query: "Leibniz Butterkeks", nameMust: ["leibniz", "butterkeks"], wikiTitle: "Leibniz-Keks" },
  { name: "Maoam Pinballs", brand: "Haribo", query: "Maoam Pinballs", nameMust: ["maoam", "pinball"], wikiTitle: "Maoam" },
  { name: "Nimm Zwei Soft", brand: "Storck", query: "Nimm 2 Soft", nameMust: ["nimm", "soft"], wikiTitle: "Nimm2" },
  { name: "Pez Bonbons", brand: "PEZ", query: "PEZ Bonbon", nameMust: ["pez"], wikiTitle: "PEZ" },
  { name: "Pom-Bär Ketchup", brand: "Lorenz", query: "Pom-Bär Ketchup", nameMust: ["pom"], wikiTitle: "Pom-Bär" },
  { name: "Pringles Cheese & Onion", brand: "Pringles", query: "Pringles Cheese Onion", nameMust: ["pringles", "cheese"], wikiTitle: "Pringles" },
  { name: "Ritter Sport", brand: "Ritter Sport", query: "Ritter Sport Schokolade", nameMust: ["ritter sport", "ritter-sport"], wikiTitle: "Ritter_Sport" },
  { name: "Sour Skittles", brand: "Skittles", query: "Sour Skittles", nameMust: ["skittles", "sour"], wikiTitle: "Skittles" },
  { name: "Liebesperlen", brand: "Liebesperlen", query: "Liebesperlen Bonbon", nameMust: ["liebesperlen"], wikiTitle: "Liebesperle" },
  { name: "Tic Tac Fresh Mint", brand: "Ferrero", query: "Tic Tac Fresh Mint", nameMust: ["tic tac", "tictac", "mint"], wikiTitle: "Tic_Tac" },
  { name: "Tic Tac Fresh Orange", brand: "Ferrero", query: "Tic Tac Fresh Orange", nameMust: ["tic tac", "tictac", "orange"], wikiTitle: "Tic_Tac" },
  { name: "Haribo Goldbären", brand: "Haribo", query: "Haribo Goldbären", nameMust: ["goldbär", "goldbaer", "gold-bear"], wikiTitle: "Goldbär" },
  { name: "Haribo Color-Rado", brand: "Haribo", query: "Haribo Color-Rado", nameMust: ["color", "rado"], wikiTitle: "Haribo" },
  { name: "Haribo Tropifrutti", brand: "Haribo", query: "Haribo Tropifrutti", nameMust: ["tropi"], wikiTitle: "Haribo" },
  { name: "Toblerone", brand: "Mondelez", query: "Toblerone", nameMust: ["toblerone"], wikiTitle: "Toblerone" },
  { name: "Ahoj-Brause", brand: "Ahoj-Brause", query: "Ahoj Brause", nameMust: ["ahoj"], wikiTitle: "Ahoj-Brause" },
  { name: "Balisto Korn-Mix", brand: "Mars", query: "Balisto Korn-Mix", nameMust: ["balisto"], wikiTitle: "Balisto" },
  { name: "Zetti Bambina", brand: "Zetti", query: "Zetti Bambina", nameMust: ["bambina"], wikiTitle: "Goldeck_Süßwaren" },
  { name: "Dickmann's Schokoküsse", brand: "Dickmann's", query: "Dickmann Schokoküsse", nameMust: ["dickmann"], wikiTitle: "Schokokuss" },
  { name: "Dominosteine", brand: "Dominosteine", query: "Dominosteine", nameMust: ["dominostein", "dominos"], wikiTitle: "Dominostein" },
  { name: "Edle Tropfen in Nuss", brand: "Trumpf", query: "Edle Tropfen in Nuss Trumpf", nameMust: ["edle", "tropfen"], wikiTitle: "Trumpf_Schokolade" },
  { name: "Erfrischungsstäbchen", brand: "Erfrischungsstäbchen", query: "Erfrischungsstäbchen", nameMust: ["erfrischungsstäb", "erfrischungsstaeb"], wikiTitle: "Erfrischungsstäbchen" },
  { name: "Esspapier", brand: "Esspapier", query: "Esspapier", nameMust: ["esspapier", "ess-papier"], wikiTitle: "Esspapier" },
  { name: "Geleebananen", brand: "Geleebananen", query: "Geleebananen Schokolade", nameMust: ["geleebanan", "gelee-banan"], wikiTitle: "Bananenschokolade" },
  { name: "Haribo Phantasia", brand: "Haribo", query: "Haribo Phantasia", nameMust: ["phantasia"], wikiTitle: "Haribo" },
  { name: "Haribo Schlümpfe", brand: "Haribo", query: "Haribo Schlümpfe", nameMust: ["schlümpf", "schluempf", "smurf"], wikiTitle: "Haribo" },
  { name: "Katjes Yoghurt-Gums", brand: "Katjes", query: "Katjes Yoghurt Gums", nameMust: ["yoghurt", "joghurt"], wikiTitle: "Katjes", imageOverride: "https://commons.wikimedia.org/wiki/Special:FilePath/Katjes_Joghurt-Gums_(0877).jpg?width=600" },
  { name: "Knoppers", brand: "Storck", query: "Knoppers", nameMust: ["knoppers"], wikiTitle: "Knoppers" },
  { name: "Zetti Knusperflocken", brand: "Zetti", query: "Zetti Knusperflocken", nameMust: ["knusperflocken"], wikiTitle: "Goldeck_Süßwaren" },
  { name: "Marzipankartoffeln", brand: "Marzipankartoffeln", query: "Marzipankartoffeln Weihnachten", nameMust: ["marzipankartoffel"], wikiTitle: "Marzipan" },
  { name: "Milka Alpenmilch", brand: "Milka", query: "Milka Alpenmilch", nameMust: ["milka", "alpenmilch", "alpine"], wikiTitle: "Milka_(Marke)" },
  { name: "Mon Chéri", brand: "Ferrero", query: "Mon Chéri", nameMust: ["mon", "cheri", "chéri"], wikiTitle: "Mon_Chéri" },
  { name: "Nimm2 Classic", brand: "Storck", query: "Nimm 2 Bonbon", nameMust: ["nimm"], wikiTitle: "Nimm2" },
  { name: "Aldi Nussknacker", brand: "Choceur", query: "Choceur Nussknacker Aldi", nameMust: ["nussknacker"] },
  { name: "Ritter Sport Marzipan", brand: "Ritter Sport", query: "Ritter Sport Marzipan", nameMust: ["ritter", "marzipan"], wikiTitle: "Ritter_Sport" },
  { name: "Rumkugeln", brand: "Rumkugeln", query: "Rumkugeln Schokolade", nameMust: ["rumkugel"], wikiTitle: "Rumkugel" },
  { name: "Schogetten", brand: "Schogetten", query: "Schogetten Schokolade", nameMust: ["schogetten"], wikiTitle: "Schogetten" },
  { name: "Schaumzucker-Speck", brand: "Schaumzucker", query: "Schaumzucker Speck", nameMust: ["schaumzucker"], wikiTitle: "Schaumzucker" },
  { name: "Snickers", brand: "Mars", query: "Snickers", nameMust: ["snickers"], wikiTitle: "Snickers" },
  { name: "Toffifee", brand: "Storck", query: "Toffifee", nameMust: ["toffifee"], wikiTitle: "Toffifee" },
  { name: "Twix", brand: "Mars", query: "Twix", nameMust: ["twix"], wikiTitle: "Twix" },
  { name: "Werther's Original", brand: "Storck", query: "Werthers Original", nameMust: ["werther"], wikiTitle: "Werther's_Original" },
  { name: "Yogurette", brand: "Ferrero", query: "Yogurette", nameMust: ["yogurette"], wikiTitle: "Yogurette" },
  { name: "Nesquik", brand: "Nestlé", query: "Nesquik Kakao", nameMust: ["nesquik"], wikiTitle: "Nesquik" },
  { name: "Hubba Bubba", brand: "Wrigley's", query: "Hubba Bubba Kaugummi", nameMust: ["hubba", "bubba"], wikiTitle: "Hubba_Bubba" },
];
